apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

# This creates the OIDC provider required for the VPC CNI
iam:
  withOIDC: true

managedNodeGroups:
  - name: spot
    instanceTypes: ["c5.large","c5a.large","c6i.large"]
    spot: true
    desiredCapacity: 2
    # Ensure this section is indented exactly like this
    iam:
      withAddonPolicies:
        vpcCNI: true
        cloudWatch: true
        autoScaler: true